services:
  postgres-test:
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"

  neo4j-test:
    image: neo4j:5.12
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687" 