services:
  redis:
    image: redis:7-alpine
    container_name: emc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass Zqz112233
    restart: unless-stopped

volumes:
  redis_data: