services:
  postgres:
    image: postgres:15-alpine
    container_name: emc_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zqz112233
      POSTGRES_DB: emc_knowledge
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: emc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass Zqz112233
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: